#!/bin/bash

export CFLAGS='-ffast-math'
export FFLAGS=$CFLAGS
export CXXFLAGS=$CFLAGS

# read optional argument destdir (where to place package file)
# default is the current directory
destdir=${1-.}

# create a temporary directory for installing files
installdir=$(mktemp --directory)
# and ensure it's cleaned on exit
trap "rm -rf $installdir" EXIT

pkgname='hic-hvq'
pkgdir="$installdir/$pkgname"

# build each model
for i in models/*/; do
  pushd $i
  
  # determine whether to build with CMake or python
  if [[ -f install-pythia ]]; then
    ./install-pythia $pkgdir 
  elif [[ -f CMakeLists.txt ]]; then
    # create build directory and run cmake if necessary
    if [[ -d build ]]; then
      cd build
    else
      mkdir build && cd build
      cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/ \
        .. || exit 1
    fi
    # compile and install to the temporary directory
    make --jobs=$(nproc) DESTDIR=$pkgdir install || exit 1
  elif [[ -f setup.py ]]; then
    # install python packages
    python3 setup.py install \
      --no-compile \
      --root=$pkgdir \
      --prefix= \
      || exit 1

    # let python find packages in the temporary directory -- this is necessary
    # because generating the eos table for vishnew requires frzout (note frzout
    # installs first because it's alphabetically ahead)
    export PYTHONPATH=$PYTHONPATH:"$(echo $pkgdir/lib*/python*/site-packages)"
  else
    echo "unknown build system for model $i"
    exit 1
  fi


  popd
done

# install the event runner script
install -v models/run.py models/run-urqmd $pkgdir/bin

# create tgz for distributing to each job
tar --verbose --create --gzip --file $destdir/$pkgname.tar.gz \
  --directory $installdir $pkgname
