#!/bin/bash

# read arguments
inputfile=$1

export pkgname='hic-hvq'
tar xzf $pkgname.tar.gz
# set environment variables
prefix="$(pwd)/$pkgname"
export PATH="$prefix/bin:$PATH"
export XDG_DATA_HOME="$prefix/share"
export PYTHONPATH="$prefix/lib/python3.6/site-packages:$prefix/lib64/python3.6/site-packages"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$prefix/lib"

# run events
run.py @$inputfile results.dat || exit 1

