#!/bin/bash

# gather system data
uname -nr

# read arguments
inputfile=$1

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module purge
module load python/3.5.2 all-pkgs gcc/6.2.0 boost/1.62.0-cxx11 gsl/2.3 libicu/4.2.1
module load hdf5/1.8.20-cxx11
module list
# unpack package
export pkgname='hic-hvq'
tar xzf $pkgname.tar.gz
# set environment variables
prefix="$(pwd)/$pkgname"
export PATH="$prefix/bin:$PATH"
export XDG_DATA_HOME="$prefix/share"
export PYTHONPATH="$prefix/lib/python3.6/site-packages:$prefix/lib64/python3.6/site-packages"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$prefix/lib"
echo $PYTHONPATH

# run events
run.py @$inputfile results.dat || exit 1

